### ISSUE TITLE
changes feeds dropping results (funky behavior)

### ISSUE THREAD

**Issue by bhurlow** [apa512/clj-rethinkdb#118]
I've been running into some confusing behavior when trying to use changes feeds. It seems that when I make inserts too close together (< 250ms apart) not all of them come out the other end in the changes stream.

Here's a lein script to demonstrate,
You can try it out using [lein-exec](https://github.com/kumarshantanu/lein-exec)
I've tried this on rethinkdb `v2.2.1`
```clj
(use '[leiningen.exec :only  (deps)])

(deps '[[com.apa512/rethinkdb  "0.11.0"]
        [org.clojure/core.async  "0.2.374"]])

(require '[rethinkdb.query :as r] :reload)
(require '[clojure.core.async :refer  (<! >! go go-loop thread take! <!! >!! chan close!)])

(def conn (r/connect :host "rethink"))

(defn test-insert [x]
  (-> (r/db "test")
      (r/table "test")
      (r/insert {:myinsert x})
      (r/run conn)))

;; this makes a cursor
(defn watch-table []
  (-> (r/db "test")
      (r/table "test")
      (r/changes)
      (r/run conn)))

;; pump cursor activity into channel inside thread
(defn feed-chan [cursor]
  (let [out (chan)]
    (thread
     (while true
      (>!! out (first cursor))))
    out))

;; keep track of what we get back 
(def change-feed-responses (atom 0))

;; handle feed results with f 
(defn attach-hander-thread [feed f]
  (thread
    (while true
      (println "received" (:myinsert (:new_val (<!! feed))))
      (swap! change-feed-responses inc))))

(def mycursor (watch-table))
(def myfeed (feed-chan mycursor))

(attach-hander-thread myfeed
  (fn [x] (println "received:" (:myinsert x))))

(def inserts-made (atom 0))

(doseq [x (range 10)]
  (test-insert x)
  (swap! inserts-made inc))

(println "awating all results .... ")
(Thread/sleep 2500)
(println "made:" @inserts-made "and received" @change-feed-responses "responses")
```

Has anyone else found issues like this or had problems with changes feeds?

**Comment by bhurlow** [comment]
@danielcompton @apa512 

Hi! Have either of you had an issues with changes feeds like this? Maybe I'm consuming the cursors wrong..

**Comment by danielcompton** [comment]
Hey, I haven't used change feeds much in this capacity (I've been using them on my async branch in a different way). If you enable TRACE logging by setting 

```xml
<logger name="rethinkdb.net" level="INFO"/>
```

to 

```xml
<logger name="rethinkdb.net" level="TRACE"/>
```

in your `logback.xml` you will be able to see all of the messages being sent and received. This might help pin down the issue a bit more. I'll take a look when I get a chance as well.

**Comment by dignati** [comment]
I think I'm getting this behavior as well. I will try to tweak the timeout and see if this has an effect.

**Comment by dignati** [comment]
Removing the timeout (as has been mentioned in other issues) did not improve the situation.

**Comment by apa512** [comment]
That's annoying. I will try to find some time to look into this.

**Comment by dignati** [comment]
Enabling the logs shows that all results from the changefeed arrive and get parsed.

I think it matters how the cursor is read. Reading within a async channel drops results but waiting for some period of time and then reading the cursor at once gives (me) all of the results.

**Comment by dignati** [comment]
So this works:

```
(deftest changefeeds
  (with-open [conn (r/connect :db test-db )]
    (let [inserts (atom #{})
          responses (atom #{})
          cursor (-> (r/table test-table)
                     (r/changes {:squash false :include-initial true})
                     (r/run conn))]
      (doseq [x (range 10)]
        (-> (r/table test-table)
            (r/insert {:myinsert x})
            (r/run conn))
        (swap! inserts
               conj
               x))
      (reset! responses (into #{} (comp (map :new_val) (map :myinsert) (take 10)) cursor))
      (is (= @inserts @responses)))))
```

but this does not:

```
(deftest changefeeds
  (with-open [conn (r/connect :db test-db )]
    (let [inserts (atom #{})
          responses (atom #{})
          cursor (-> (r/table test-table)
                     (r/changes {:squash false :include-initial true})
                     (r/run conn))
          feed (let [out (async/chan)]
                 (async/thread
                   (loop [c cursor]
                     (if-let [f (first c)]
                       (do (async/>!! out f)
                           (recur (rest c)))
                       (throw (RuntimeException. "Cursor head was nil")))))
                 out)]
      (async/thread
        (while true
          (swap! responses conj (:myinsert (:new_val (async/<!! feed))))))
      (Thread/sleep 2500)
      (doseq [x (range 10)]
        (-> (r/table test-table)
            (r/insert {:myinsert x})
            (r/run conn))
        (swap! inserts
               conj
               x))
      (Thread/sleep 2500)
      (is (= @inserts @responses)))))
```

**Comment by dignati** [comment]
I believe this to be a problem with the `Cursor`. Calling `seq` on the changefeed cursor and not using the cursor afterwards prevents dropping results. If I'm understanding `lazy-seq` and `Cursor` correctly, using the `Cursor` as `ISeq` (eg. with `first` or `rest` as in the examples above) will create a new `lazy-seq`. What you'd want instead is the same `lazy-seq` every time you use a `Cursor` as an `ISeq`. So you can work around this problem as is by calling `seq` on a `Cursor` once yourself and not using the `Cursor` afterwards. 

I think it would be better to prevent this altogether. Caching the `lazy-seq` in the `Cursor` object would be possible but also introduce a memory leak as the head of the `lazy-seq` is never released. I don't think we'd want that for long-running changefeeds. Another alternative could be to return an `atom` of the results and gradually append new results as they are coming in over the network. The user could then use the `atom` in a threadsafe manner to release unused elements inside the atom. The third (and in my opinion best) option could be the core.async api proposed in @danielcompton's PR #55

**Comment by bhurlow** [comment]
@dignati I agree that just pumping into the `lazy-seq` could be risky for memory management. One advantage of a lazy seq is that it could be converted to a proper stream abstraction by the end user (manifold for example). Looks like @danielcompton's pr looks almost there!

**Comment by apa512** [comment]
Should work now using the latest release. Let's reopen otherwise.

**Comment by bhurlow** [comment]
@apa512 the aleph release?

**Comment by apa512** [comment]
Yes.

**Comment by bhurlow** [comment]
Great! Netty and aleph have been treating me quite well. Will give it a spin
