### ISSUE TITLE
have connections implement Closeable

### ISSUE THREAD

**Issue by sritchie** [apa512/clj-rethinkdb#12]
Rather than create a cursor protocol, what do you think of using `java.io.Closeable`?

I tried to implement a wrapper for connections that would allow you to use `with-open` on them, but unfortunately the `IAtom` interface was only introduced in Clojure 1.7.0.

```clojure
(defn conn-atom
  "Returns an atom-like wrapper around a connection that's closeable."
  [conn-map]
  (let [a (atom conn-map)]
    (reify
      Closeable
      (close [_] (close a))
      IDeref (deref [_] @a)
      IAtom
      (swap [_ f] (.swap a f))
      (swap [_ f x] (.swap a f x))
      (swap [_ f x y] (.swap a f x y))
      (swap [_ f x y more] (.swap a f x y more))
      (reset [_ new] (.reset a new))
      (compareAndSet [_ old new]
        (.compareAndSet a old new)))))
```

**Comment by apa512** [comment]
:+1: I like it. Would make the whole connection story much better. Requiring Clojure 1.7 is kind of a deal breaker though :crying_cat_face:

**Comment by sritchie** [comment]
I think we can fix this by using `proxy` to create an instance of `clojure.lang.Atom` that also implements `Closeable`. If you're into it I can play around with that.

**Comment by apa512** [comment]
Sounds like a good idea.

**Comment by sritchie** [comment]
Closing this in favor of #13
