### ISSUE TITLE
table-create does not support default db

### ISSUE THREAD

**Issue by lsenta** [apa512/clj-rethinkdb#124]
Hi, first of all, thanks for maintaining clj-rethinkdb, it's pretty sweet to use.

The first line of the documentation says

```
  (comment "This is equivalent to the previous query; db on connection is implicitly
  used if no db is provided."
  (-> (r/table-create "authors")
      (r/run conn)))
```

Which is actually not the case, see [doc](http://apa512.github.io/clj-rethinkdb/rethinkdb.query.html#var-table-create) and [source](https://github.com/apa512/clj-rethinkdb/blob/0.10.1/src/rethinkdb/query.clj#L62), neither on [0.11](https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/query.cljc#L77-L80)

**Comment by apa512** [comment]
Fixed in the latest version.
