### ISSUE TITLE
An example for abort changes feed.

### ISSUE THREAD

**Issue by DogLooksGood** [apa512/clj-rethinkdb#130]
If I start a change feeds in `go` block, how can I stop it?
```clojure
(go (let [changes (-> (r/db "test")
                      (r/table "message")
                      (r/order-by {:index (r/desc "time")})
                      (r/limit 10)
                      (r/changes)
                      (r/run conn))]
         (for [change changes]
             (ws-send! change))))
```

**Comment by danielcompton** [comment]
Call `close` on it.

**Comment by danielcompton** [comment]
Oops, I mean send-stop-query https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/net.clj#L165

**Comment by DogLooksGood** [comment]
`send-stop-query` works fine!
Thanks a lot, but still think it should be mentioned in README.

**Comment by danielcompton** [comment]
For sure, happy to take a PR on this.

**Comment by danielcompton** [comment]
Whoops I was correct the first time but had the wrong place. Use `close` https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/net.clj#L25

**Comment by DogLooksGood** [comment]
Using `send-stop-query` directly works in `0.11.0`, but failed in `0.12.x-SNAPSHOT`.
I've changed to `close`.

**Comment by apa512** [comment]
:+1:

**Comment by danielcompton** [comment]
Yeah, `send-stop-query` is really an impl detail.
