### ISSUE TITLE
r/merge is not consistent with ReQL

### ISSUE THREAD

**Issue by lukaszkorecki** [apa512/clj-rethinkdb#131]
I found a strange issue with `r/merge` function. 
I usually prototype queries in the data explorer in Rethinkdb web and then translate them into Clojure.

So given this example session:
```javascript

// First - let's create the tables and seed them with data

r.db('test').tableCreate('labels');
r.db('test').tableCreate('files');

// labels
r.db('test').table('labels').insert(
[ { id: 'abc123', name: 'foo'},
  { id: 'def234', name: 'bar' }
]);

// files files:

r.db('test').table('files').insert(
[
  { id: 1, label_id: ['abc123', 'def234']},
  { id: 2, label_id: ['abc123'] }
]
);

// I want to efficiently join labels into files when querying
// for them. This is the naive approach:

r.db('test').table('files').merge(function(d) {
  return  {
    labels: d('label_id').map(function(id) {
                               return r.table('labels').get(id);
                              })};
});

// this also works, note the use of r.args. 
// Also - coerceTo is required because merge doesn't
// work on slices
r.db('test').table('files').merge(function(d) {
  return { labels: r.table('labels').getAll(r.args(d('label_id'))).coerceTo('array') };
});


```

Both ways of merging data work as expected and according to query profiler have similar per characteristics (I'm skeptical of this as I haven't tested them on a bigger data set).

However when translating the above queries into Clojure + `clj-rethinkdb` I ran into an issue:

```clojure
;; assuming that tables & data created above still exist)

(->
 (r/table "files")
 (r/merge (r/fn [ro]
            (let [ids (r/get-field ro :label_id)
                  labels (r/map ids
                                (r/fn [id]
                                  (->
                                   (r/table "labels")
                                   (r/get id))))]
              {:labels labels})))
 (r/run (r/connect :db "test")))


;; Output, as expected:

[
 {:id 2, :label_id ["abc123"],
  :labels [{:id "abc123", :name "foo"}]}

 {:id 1, :label_id ["abc123" "def234"],
  :labels [{:id "abc123", :name "foo"}
           {:id "def234", :name "bar"}]}]


;; However this fails:

(->
 (r/table "files")
 (r/merge (r/fn [row]
            (let [ids (r/get-field row :label_id)
                  labels (->
                          (r/table "labels")
                          (r/get-all ids)
                          (r/coerce-to "array"))]
              {:labels labels})))
 (r/run (r/connect :db "test")))



;; Error details:
;;           rethinkdb.query$run.invoke                        query.cljc: 1043
;;       rethinkdb.net/send-start-query                           net.clj:  159
;;             rethinkdb.net/send-query                           net.clj:  142
;; rethinkdb.net/make-rethink-exception                           net.clj:   14
;;                 clojure.core/ex-info                          core.clj: 4593
;; clojure.lang.ExceptionInfo: RethinkDB server: Array keys can only contain numbers, strings, bools,  pseudotypes, or arrays (got {
;;                              "id": 2,
;;                              "label_id": [
;;                                "abc123"
;;                              ]
;;                             } of type OBJECT).
;;     response: {:t 18,
;;                :e 3000000,
;;                :r
;;                ["Array keys can only contain numbers, strings, bools,  pseudotypes, or arrays (got {\n\t\"id\":\t2,\n\t\"label_id\":\t[\n\t\t\"abc123\"\n\t]\n} of type OBJECT)."],
;;                :b [1 1 "labels" 0]}
;;         type: :query-logic
```
So - rather than pulling out value of `label_id` and passing it to `get-all` it seems to be taking `row` as a whole and passing it down.

Versions:
Clojure 1.7
RethinkDB 2.2.3-1
clj-rethinkdb 0.12.2-SNAPSHOT

I've looked at the source to see if it's a low-hanging fruit bug fix (assuming it's a bug ;-)) but I couldn't find anything obvious that would cause this. With some pointers I will be happy to work on a fix

**Comment by danielytics** [comment]
Looks like a typo in your clojure code. You are not passing `ids` to `->`. Try this instead

```(->
 (r/table "files")
 (r/merge (r/fn [row]
            (let [ids (r/get-field row :label_id)
                  labels (-> ids ; ADDED ids HERE!
                          (r/table "labels")
                          (r/get-all ids)
                          (r/coerce-to "array"))]
              {:labels labels})))
 (r/run (r/connect :db "test")))```

**Comment by lukaszkorecki** [comment]
@danielytics Unfortunately that wasn't it - first (or the deepest, if you unwrap the `->` macro) call needs to be to `r/table`

**Comment by danielytics** [comment]
I noticed right after I posted, which is why I deleted it again.

**Comment by lukaszkorecki** [comment]
@danielytics ah I see :-) Github didn't refresh things fast enough

**Comment by danielytics** [comment]
What happens if you change it to `{:labels ids}` (ie, what does `ids` return)?

I'm almost certain that I've written code like this before, although I haven't used RethinkDB in a few months.

**Comment by lukaszkorecki** [comment]
@danielytics I think I tried that before. Anyway, here's the query and the result:

```clojure

(->
 (r/table "files")
 (r/merge (r/fn [ro]
            (let [ids (r/get-field ro :label_id)]

              {:labels ids})))
 (r/run (r/connect :db "test")))


[{:id 2, :label_id ["abc123"], :labels ["abc123"]} {:id 1, :label_id ["abc123" "def234"], :labels ["abc123" "def234"]}]

```

So yeah - it seems to be doing the right thing, up to the point of querying "labels" table.
Clojure driver doesn't implement `r.args` required in JS because `get-all` already expects a vector (rather than being a variadic function.

**Comment by lukaszkorecki** [comment]
Also, this works as expected:

```clojure

(->
 (r/table "files")
 (r/merge (r/fn [ro]
            (let [ids (r/get-field ro :label_id)
                   labels (->
                                (r/table "labels")
                                (r/get-all ["abc123"]) ;; "forcing" the merge with hardcoded label id
                                (r/coerce-to "array"))]
              {:labels labels})))

 (r/run (r/connect :db "test")))
```

**Comment by danielytics** [comment]
I vaguely remember there being something weird or unexpected, but don't remember what as its been too long. However, out of interest, try this (ie wrapping ids in []):

```
(->
 (r/table "files")
 (r/merge (r/fn [row]
            (let [ids (r/get-field row :label_id)
                  labels (->
                          (r/table "labels")
                          (r/get-all [ids])
                          (r/coerce-to "array"))]
              {:labels labels})))
 (r/run (r/connect :db "test")))
```

or perhaps

`(r/get-all (r/cource-to ids "array"))`

I assume that this also works if you use filter instead of get-all? (but without the index benefits)

(sorry, I can't test myself right now and don't remember what it was that I had trouble with)

**Comment by lukaszkorecki** [comment]
@danielytics I think I tried all combinations and tricks I could think of - usually I either get the original error, or an empty vector under `:labels` key because while the query works, it's not matching anything.

I'll try to do a deep dive into the source to work out what's happening

**Comment by apa512** [comment]
Oops. ```get-all``` was only designed to take a table and ids as arguments, causing queries to be sent to RethinkDB unevaluated.

Your failing query should work as expected now.

**Comment by apa512** [comment]
Clarification: I've added args, which must be used like in the JS version.

**Comment by lukaszkorecki** [comment]
@apa512 That's awesome - thanks a lot. I'll test `0.13.3-SNAPSHOT` today :+1:
