### ISSUE TITLE
Cyclic dependency in example?

### ISSUE THREAD

**Issue by favetelinguis** [apa512/clj-rethinkdb#137]
I get the following error when trying to first example in README:

```
user> (require '[rethinkdb.query :as r])
CompilerException java.lang.Exception: Cyclic load dependency: [ /rethinkdb/query ]->/rethinkdb/core->[ /rethinkdb/query ], compiling:(rethinkdb/core.clj:1:1) 
```

Is this default or am I missing some basics?

**Comment by apa512** [comment]
Very strange. What version are you using?

**Comment by favetelinguis** [comment]
0.15.12

**Comment by apa512** [comment]
Sorry, I'm just not seeing why core would try to load query. There must be something strange with your environment or someone else should have experienced this.

Mind showing me your project.clj? Assuming you're using clj-rethinkdb in some project and not just running a REPL from the cloned repo.

**Comment by favetelinguis** [comment]
Sure, this is rly bugging me, cant understand what is wrong.
```
(defproject rethinkdb "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [com.apa512/rethinkdb "0.15.12"]])
```

**Comment by apa512** [comment]
Oh, that explains it. Try calling your project something other than rethinkdb.

clj-rethinkdb already provides rethinkdb.core and I'm guessing your template created that namespace too.

**Comment by favetelinguis** [comment]
That did the trick! Thanks
