### ISSUE TITLE
Change feed into core.async channel

### ISSUE THREAD

**Issue by favetelinguis** [apa512/clj-rethinkdb#139]
Are there any example on how to turn a change feed into core.async channel that receives each update?

**Comment by danielytics** [comment]
The simplest way is to pass `{:async true}` to `run`, which will then return a channel that will receive the changes:

https://github.com/apa512/clj-rethinkdb/blob/3ee5796643fe73e55c517fd2dc8da17304fe6bf3/test/rethinkdb/core_test.clj#L171-L174

If you need the changes to go into an existing channel, you can use `(core.async/pipe chan-from-run destination-chan)`

**Comment by favetelinguis** [comment]
works fine, thanks!

**Comment by dignati** [comment]
Are your sure that the connection you are using stays open? For example, wrapping the above in a `with-open` would not work because the go-loop returns immediately so the connection gets closed and all running queries are stopped.

**Comment by favetelinguis** [comment]
Yes the connection is open, it is stored in an atom.

**Comment by apa512** [comment]
It still sounds to me like you're passing in a non-active connection somewhere. Can you show a working example where this happens?

The previous example certainly wouldn't work if conn is an atom.

**Comment by favetelinguis** [comment]
Sorry, needed a secound pair of eyes, I was missing:

```(r/run @conn {:async? true})```
