### ISSUE TITLE
UUID handling

### ISSUE THREAD

**Issue by jwr** [apa512/clj-rethinkdb#15]
I'm not sure if that is actually an issue, so I'm just posting it for consideration. I am trying to insert data that contains (pre-generated) UUIDs. This produces the error:

    Unhandled java.lang.Exception
    Don't know how to write JSON of class java.util.UUID
                      json.clj:  385  clojure.data.json/write-generic

[the rest of the backtrace omitted for clarity]

Now, on one hand perhaps it was the intention to only handle strings (and perhaps numeric types) — on the other hand, UUIDs are pretty ubiquitous, RethinkDB uses them internally as well. Should this be handled, or should I just convert my UUIDs to strings before trying to insert data?

**Comment by apa512** [comment]
I like the idea of handling UUIDs in the client. Fix coming right up.

**Comment by apa512** [comment]
Now accepts UUIDs.

**Comment by jwr** [comment]
Cool, thank you!
