### ISSUE TITLE
group by multiple things supported?

### ISSUE THREAD

**Issue by thedavidmeister** [apa512/clj-rethinkdb#154]
In the data explorer I can do this:

`r.table('foo').group('a', 'b')`

And it works as expected.

In clojure though, `(r/group "a" "b")` does not work, and obvious things i tried like `(r/group "a") (r/group "b")` and `(r/group ["a" "b"])` didn't work either.

Is there a way to make this work?

**Comment by apa512** [comment]
You're right. Group with multiple fields was missing. Sorry about that.

Fixed in ```0.15.19``` which was released just a few minutes ago. ```(r/group ["a" "b"])``` is how you use it.

**Comment by thedavidmeister** [comment]
awesome.

I created a compound index in the meantime, and grouped on that, but good to extend the API :)
