### ISSUE TITLE
eq-join produces a cursor object

### ISSUE THREAD

**Issue by jwr** [apa512/clj-rethinkdb#16]
I am trying to do an eq-join:

     (-> (r/db db)
         (r/table "parts")
         (r/eq-join :id (db-table "stock") {:index :part-id})
         (r/run conn))

…but this produces a `#<Cursor rethinkdb.net.Cursor@2c9b666e>`, which is not what I'd expect after reading http://www.rethinkdb.com/docs/table-joins/

Adding an (r/zip) just before (r/run conn) produces the expected result.

I am not sure if this is intended or not. It certainly is unexpected.

More generally, I could not get a number of things to work:

* create a secondary index on multiple fields (but not using a function)
* get on nested fields (actually, I found an explanation for that one in one of the closed issues)
* create a secondary index on nested fields
* eq-join examples with merge and subqueries from  http://www.rethinkdb.com/docs/table-joins/

I think clj-rethinkdb could really benefit from more examples. I could actually help with writing documentation, but for the moment I can't figure out how many things should work. Perhaps someone could extend the basic example so that it does more things from the RethinkDB tutorials?

**Comment by apa512** [comment]
Getting a cursor is actually the expected outcome, though I agree it's not very intuitive. Cursors implement Seqable so you can for example turn it into a vector with ```into [] ``` or use ```take``` to avoid loading the entire result set.

Examples are very lacking and I'm too lazy to write them. Perhaps the best way for now is to look at the tests.

**Comment by jwr** [comment]
Oh. Sorry — I read the RethinkDB tutorial on table joins and they show the pretty {"left": {...}, "right": {...}} output, without mentioning a cursor once. It turns out that one can learn about cursors by digging deeper into JavaScript API documentation.

I did look at the tests, but for example for indexes they also only contain a fairly simple example of an index created using a custom function.

Like I said, I'm willing to do some work on this, but I can't find a good way to get started. I've been banging my head against a wall for a while now, and the only way forward that I can see is to start back from the JSON protocol and work back through the code from there, trying to figure out what the Clojure form of rdb commands is. Can you suggest a better approach?

**Comment by apa512** [comment]
The client is pretty much a direct mapping of the underlying JSON protocol so I guess https://github.com/rethinkdb/rethinkdb/blob/v2.0.x/src/rdb_protocol/ql2.proto could be useful. Either that or reading query.clj.

The same functions are used for creating indexes and querying, so the syntax for creating a secondary index on a nested field is the same as get on a nested field.

Is there anything else you've been having trouble with?

**Comment by jwr** [comment]
No, thanks — I'm figuring things out from the ground up and making progress. I will probably make a pull request in a while, with expanded examples, so that others have an easier start. I think this issue can be closed.

BTW, the idea that I should get a structure with "left" and "right" fields was from a RethinkDB tutorial, this is why I was surprised that I got a cursor. That cursor additionally explodes in your face once it goes out of (with-open) connection scope, so it's a double whammy.
