### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by larshelgklp** [apa512/clj-rethinkdb#169]
Is connection pooling supported?

**Comment by danielytics** [comment]
No. There was a lengthy discussion about that here #23 and the verdict was that [RethinkDB Proxy Nodes](https://www.rethinkdb.com/docs/sharding-and-replication/#running-a-proxy-node) give you _almost_ everything that connection pools would.

Maybe take a look at that discussion first and if your use case isn't covered, perhaps open a more specific ticket.

**Comment by larshelgklp** [comment]
Thanks for the quick reply. Was more of a question than issue. Will take a look at the discussion. Just close this ticket.

**Comment by danielytics** [comment]
In case you missed it, I edited my comment to add more info about how proxy nodes help with connection pooling.

(I don't have access rights to close the issue, so you or one of the admins will have to do it, if you feel the question is sufficiently answered)

**Comment by danielytics** [comment]
Note also that you can issue many queries asynchronously through the same connection (which is another use case of connection pools: multiple queries on blocking connections).

**Comment by danielcompton** [comment]
I can forsee needing some connection pools in our app, even when using proxy nodes, so this may come in the future, either in this project, or a sister project.
