### ISSUE TITLE
Unwanted stacktraces

### ISSUE THREAD

**Issue by maxp** [apa512/clj-rethinkdb#173]
There are some reasons not to use particular logging system in a library.
Because of long unwanted error stacktraces produced by uncontrolled logger.
(App uses 'timbre' logging, not clojure.tools.logging).

Ex-info is a good and sufficient choice.

In some cases database error like 'table already exists' is not a real error 
but desired behavior and should not produce error messages.

Please remove those lines
https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/net.clj#L7
https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/net.clj#L30

https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/core.clj#L4
https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/core.clj#L74
https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/core.clj#L87

**Comment by lukaszkorecki** [comment]
You can silence these by creating appropriate log4j config - there's no need to remove logging at all (I for one find it very useful)

**Comment by maxp** [comment]
I don't use log4j stuff at all and was very happy to get rid of that!
Now I use timbre logging but on application level but not inside the library!

Log noise from inside is unwanted side effect.
Correct exception handling and already inplemented "throw ex-info" is a lot more wise solution.

The library should just throw an exception but application layer will decide what to do with that - beep, print, log or whatever. Only application really knows is that exception an error or a warning or just an ignorable info.

Using third party logging tools forces developer to deal with another different format/config/loglevel| and so on.

**Comment by maxp** [comment]
Look at that line - https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/net.clj#L30
`(log/error ex)`

I have exactly the same code in outer catch block.
Duplicating error messages is not so useful.

**Comment by danielcompton** [comment]
clj-rethinkdb uses `clojure.tools.logging` for logging. Timbre has an [adapter](https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre/tools/logging.clj) for it so you can use that. If you don't like the logging levels, you can set them yourself with timbre?

**Comment by danielcompton** [comment]
Although, you make a good argument to not log the exception as an error, will look into that.

**Comment by maxp** [comment]
There are only three log/... calls that I mentioned above. 
And in every case correct "throw" statement _already_ implemented.

**Comment by danielcompton** [comment]
I've removed the error calls, though kept the trace. If you want more control over what clj-rethinkdb is logging, then supply a logging config.

**Comment by maxp** [comment]
Great. Thank you.
