### ISSUE TITLE
add a `grant` method

### ISSUE THREAD

**Issue by nha** [apa512/clj-rethinkdb#177]
The `grant` method is missing (Java driver doc: https://www.rethinkdb.com/api/java/grant/ ).

It should be currently possible to work around this either by:
- falling back to the Java driver (https://www.rethinkdb.com/api/java/grant/)
- writing directly to the system tables ( https://www.rethinkdb.com/docs/system-tables/ )

**Comment by danielcompton** [comment]
We don't currently use the Java driver, but we can provide this by adding a new term. Happy to take a PR for this. If you take a look at the `rethinkdb.query` namespace you can see how the terms are defined, happy to help if you have any questions. Otherwise I'll take a look at this when I have time.

**Comment by nha** [comment]
I started working on this at https://github.com/nha/clj-rethinkdb

I have a test failure though: `Exception in thread "async-dispatch-24" java.lang.IllegalArgumentException: No enum constant rethinkdb.Ql2.Term.TermType.GRANT`

Does that mean I have to use/edit https://github.com/apa512/rethinkdb-protobuf ?
If yes could you clarify the relation between these two projects ?

**Comment by nha** [comment]
It seems the purpose of this repository is to have this file available for Clojure:

https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/ql2.proto

Here is what I tried so far :

- edit the rethinkdb-protobuf repository
- install https://github.com/ninjudd/lein-protobuf
- run `lein do clean, protobuf` or `lein install` inside https://github.com/apa512/rethinkdb-protobuf fails for me (apparently I am missing automake-1.14 which is not in homebrew)

```
Running 'make'
 cd . && /bin/sh /Users/nha/.lein/cache/lein-protobuf/protobuf-2.6.1/missing automake-1.14 --foreign
 >  /Users/nha/.lein/cache/lein-protobuf/protobuf-2.6.1/src/protoc ql2.proto --java_out=/Users/nha/repo/vendor/rethinkdb-protobuf/target/protosrc -I. -I/Users/nha/repo/vendor/rethinkdb-protobuf/target/proto -I/Users/nha/repo/vendor/rethinkdb-protobuf/resources/proto
java.io.IOException: Cannot run program "/Users/nha/.lein/cache/lein-protobuf/protobuf-2.6.1/src/protoc" (in directory "resources/proto"): error=2, No such file or directory
 at java.lang.ProcessBuilder.start (ProcessBuilder.java:1048)
```

Happy to submit a PR to https://github.com/apa512/rethinkdb-protobuf if needed after I get to test it locally (whole file or only GRANT) ?

**Comment by danielcompton** [comment]
I've deployed new protobuf definitions up to 2.3.0. I had trouble redeploying on my new computer, I needed to install automake-1.14 for it to build. See http://stackoverflow.com/questions/29591295/clojure-protobuf-cannot-run-program-path-protoc-in-directory-resources-pro for more details.

**Comment by nha** [comment]
Thanks that was indeed the problem. I also had to remove lein-protobuf from my plugin list.
Would you be interested in a small addition to the README/Wiki to describe how to get started on contributing ?

I think that, apart from formatting issues I have a PR ready at https://github.com/nha/clj-rethinkdb

**Comment by danielcompton** [comment]
Will add a note on contributing.

Feel free to open a PR against this repo when you're ready. Also, I just had a quick look and saw a bunch of whitespace changes. It's much easier for me to review and accept a change if there aren't extra whitespace changes. Thanks!

**Comment by nha** [comment]
Closing since the patch has been merged. Thanks!
