### ISSUE TITLE
add r/expr term

### ISSUE THREAD

**Issue by nha** [apa512/clj-rethinkdb#178]
The `expr` query is missing: https://www.rethinkdb.com/api/javascript/expr/

My use case: it seems necessary for a workaround to create tables atomically:

```
(defn ensure-db
  "atomic ensure-db"
  [db]
  (r/branch (r/contains (r/db-list) db)
            (r/expr {:config_changes [] :dbs_created 0})
            (r/db-create db)))
```

**Comment by apa512** [comment]
Are you getting any errors?

I just tried
```clojure
(r/run (r/branch (r/contains (r/db-list) "rethinkdb") {:config_changes [] :dbs_created 0} (r/db-create "rethinkdb")) conn)
```
and that worked fine, returning a normal Clojure map when the DB exists.

**Comment by danielcompton** [comment]
I don't think `expr` is needed in Clojure as we have syntax for data literals already?

**Comment by nha** [comment]
Ah right then sorry for the noise - closing this issue.
