### ISSUE TITLE
minval and maxval are missing

### ISSUE THREAD

**Issue by jwr** [apa512/clj-rethinkdb#18]
I thought I'd just implement them and send you a pull request, but after a quick look I'm not so sure — I think it would be better to have all constants as constants, not functions, so that we can write

    (r/between [1 r/maxval] {:index "my-index"})

instead of:

    (r/between [1 (r/maxval)] {:index "my-index"})

**Comment by apa512** [comment]
I didn't know these existed. Added now.

**Comment by jwr** [comment]
Much appreciated. Thanks!
