### ISSUE TITLE
Ability to use index in distinct

### ISSUE THREAD

**Issue by royalaid** [apa512/clj-rethinkdb#186]
It doesn't appear to be possible to use an index with distinct as it currently implemented. Just curious if it would be possible to provide this?

**Comment by apa512** [comment]
Added in 1.0.0-SNAPSHOT.

```clj
(is (= (-> (r/table test-table) (r/distinct {:index "name"}) (r/run conn))
           ["Magnemite" "Pikachu"]))
```
