### ISSUE TITLE
how to use nested without?

### ISSUE THREAD

**Issue by thedavidmeister** [apa512/clj-rethinkdb#190]
i want to use `without({'right': 'id'})` as per https://www.rethinkdb.com/api/javascript/eq_join/ but i can't figure out how to get it working in `clj-rethinkdb`.

Everything I've tried either does nothing or strips _all_ the right fields.

**Comment by thedavidmeister** [comment]
nm, i just realised it needs to be `(r/without [{:right :id}])` in a vector

**Comment by apa512** [comment]
Good, you found it.

```clj-rethinkdb``` sometimes expects a sequence where the official drivers don't, and this is one of those cases.
