### ISSUE TITLE
Implement connection pooling and auto-reconnection logic

### ISSUE THREAD

**Issue by danielytics** [apa512/clj-rethinkdb#23]
It would be very useful if a connection pool could be created which can be connected to multiple servers in a cluster. Additionally, if a connection is disconnected due to a socket error, there should be an option to have the pool automatically attempt to reconnect.

**Comment by jwr** [comment]
I regularly use Carmine (https://github.com/ptaoussanis/carmine), which uses Apache Commons Pool (https://commons.apache.org/proper/commons-pool/ and see also article http://www.javaworld.com/article/2071834/build-ci-sdlc/pool-resources-using-apache-s-commons-pool-framework.html).

There are pitfalls, but they exist in every pooling approach. At least with this one we could follow what Carmine does.

**Comment by danielcompton** [comment]
https://github.com/neumino/rethinkdbdash is a RethinkDB client with connection pooling, it could be interested to look at what they do and if there's any Rethink specific logic required.

**Comment by danielytics** [comment]
My requirements for connection pools are:

1. Connection pool should support many connection to many servers 
1. Distribute connections to servers round-robin
1. Should be able to run queries against a single connection, or a pool
1. Connections should (optionally) auto-reconnect if they are disconnected
1. Connection pools should (optionally) auto-reconnect to any servers that get disconnected

Apache Commons Pool looks like it will make this easier. Should be able to use its Keyed pools to implement 1 and 2. Not sure yet how to do auto-reconnect. Does carmine automatically reconnect?

**Comment by jwr** [comment]
@danielytics No, carmine does not automatically reconnect. Making this work is much more difficult than it might seem (and I don't think it can be done reliably) because of Redis' MULTI/EXEC transactions. You just can't handle a disconnect in the middle of a MULTI/EXEC block transparently in the library.

**Comment by danielytics** [comment]
Right. RethinkDB may have similar issues - I don't know is it safe to do `START`, then disconnect/reconnect `CONTINUE`. I'll have to look into this.

**Comment by jwr** [comment]
I think it is important to understand how RethinkDB works and processes requests. I wasn't able to find a good description yet, which is why I have an uneasy feeling about both this issue and issue #20 — the way we implement async handling or connection pooling needs to be closely coupled to the way DB does it.

(with Redis it's fairly simple: Redis is single-threaded and only ever processes one command at a time)

**Comment by danielytics** [comment]
Ok, I will dig into it today and ask on the RethinkDB mailing list if needed.

**Comment by danielcompton** [comment]
The docs for [reconnect](http://rethinkdb.com/api/javascript/reconnect/) seem to imply that queries are cancelled on disconnection.

**Comment by danielcompton** [comment]
I'm almost certain that every connection is isolated. Tokens for queries only need to be unique per connection. If you drop a connection (i.e. the socket closes), then on reconnect you won't be able to send a CONTINUE with the same token.

**Comment by danielcompton** [comment]
I think that it would be much more efficient to run a RethinkDB proxy node on every server using clj-rethinkdb. http://rethinkdb.com/docs/sharding-and-replication/#running-a-proxy-node

> Once you have several machines in a RethinkDB cluster, you can improve your cluster’s efficiency by running a proxy node on each application server and having the client application connect to the proxy on localhost.

> A proxy node doesn’t store any data; instead it acts as a query router. This offers some performance advantages:

> * The proxy will send queries directly to the correct machines, reducing intracluster traffic.
> * If you’re using changefeeds, the proxy will de-duplicate changefeed messages sent from other cluster nodes, further reducing traffic.
> * The proxy node can do some query processing itself, reducing CPU load on database servers.

> To run a proxy node, simply use the proxy command line option on startup.

>     rethinkdb proxy --join hostname:29015

Original requirements list:

1. Connection pool should support many connection to many servers - not needed as proxy handles this
2. Distribute connections to servers round-robin - not needed as proxy handles this, and can route queries to server holding data
3. Should be able to run queries against a single connection, or a pool - unsure if this is needed. What is the benefit of multiple connections vs a single Socket?
4. Connections should (optionally) auto-reconnect if they are disconnected
5. Connection pools should (optionally) auto-reconnect to any servers that get disconnected - proxy will handle this

This would reduce the needs of connection pooling to:

* Connections should (optionally) auto-reconnect if they are disconnected
 
and maybe:

* Should be able to run queries against a single connection, or a pool

I'm not totally sure what benefits we would get from pooling the connections vs using a single connection. With #55, we are using protocol v4 which lets results came back out of order from requests.

As discussed earlier, auto-reconnecting queries is pretty difficult to do well, and I can't think of scenarios where I'd actually want a query to automatically reconnect. For example:

* Single read query sent but disconnected before query returns - could be useful here
* Read query that is chunked (needs to CONTINUE) - unless the Connection retains state about the query and can "fast forward" after re-executing the query to the last place the user got to, this isn't much use. It would also raise transactionality concerns, i.e. if you're reading a whole table you aren't guaranteed to get a consistent view of it (currently reads are [READ_UNCOMMITTED](http://rethinkdb.com/faq/#can-rethinkdb-reads-ever-see-stale-data) but this will change in RethinkDB 2.1)
* Changefeed query - if the connection drops, you may have lost data that changed in the meantime, so you'll probably need to rebuild your state. If you're doing a [point changefeed](http://rethinkdb.com/api/javascript/changes/), then you'll get a new `"state": "initializing"` in your change feeds that you'll need to watch out for
* Mutable queries - all bets are off with mutating queries. Anything could happen between the time the query was meant to run, and the time that is actually run (or possibly rerun).

I guess I can't see very many cases where you would want to handle reconnections. Additionally, the proxy node should be pretty resilient to network blips as it maintains a connection to all of the servers.

All that being said, I'd be interested to hear what use cases aren't covered by this.

**Comment by danielytics** [comment]
Are proxy nodes new?

They definitely meet most use cases (and do so better than we could do in
the driver).

The main place I'd like auto reconnect is if I try run a query against a
connection and that connection is down. However if we go with an error
channel approach to handling errors then I could see myself putting
reconnect logic there.
My use case is that I want to be able to restart the database without my
app breaking (so I can't simply connect once on startup, but I don't want
to wrap revert query in error handling logic for disconnected database
either).

I think proxy nodes do cover almost all of the use cases and perhaps an
error channel that I can listen for disconnects on is enough for
reconnection.

**Comment by danielytics** [comment]
I think that auto-reconnect could be quite easy to manually do if the error handling allows queries to be resubmitted (with the same token/result channel so that its transparent to the caller). I've added a separate ticket for this: #66 

Unless there are other outstanding requirements here that aren't solved by proxy nodes and proper error handling (I can't think of anything), then I think this issue is basically done. So I'm going to close it, but if there is something else that was missed, I can reopen it.
