### ISSUE TITLE
Deprecate any and all for or and and

### ISSUE THREAD

**Issue by danielcompton** [apa512/clj-rethinkdb#25]
In V0_4 of the spec, the Protocol buffer names for `any` and `all` have changed to `or` and `and` respectively. It looks like clj-rethinkdb has started using the V0_4 version of the spec (which should be backwards compatible with previous versions), however because the names have changed we will now be looking up an enum which no longer exists.

It looks like `rethinkdb.query/any` and `rethinkdb.query/all` aren't part of the tests so this wasn't picked up when the protobuf dependency changed.

One way of solving this is to deprecate `any` and `all`, and create new `or` and `and` functions which use the new term name, and then get `any` and `all` to call `or` and `and`. I'm happy to put together a PR to help on this.

```diff
git diff v1.16.0 v2.0.0 -- src/rdb_protocol/ql2.proto

diff --git a/src/rdb_protocol/ql2.proto b/src/rdb_protocol/ql2.proto
index 113ea7d..3ee6831 100644
--- a/src/rdb_protocol/ql2.proto
+++ b/src/rdb_protocol/ql2.proto
<SNIP...>
@@ -520,11 +546,9 @@ message Term {
         // statement).
         BRANCH  = 65; // BOOL, Top, Top -> Top
         // Returns true if any of its arguments returns true (short-circuits).
-        // (Like `or` in most languages.)
-        ANY     = 66; // BOOL... -> BOOL
+        OR      = 66; // BOOL... -> BOOL
         // Returns true if all of its arguments return true (short-circuits).
-        // (Like `and` in most languages.)
-        ALL     = 67; // BOOL... -> BOOL
+        AND     = 67; // BOOL... -> BOOL
         // Calls its Function with each entry in the sequence
         // and executes the array of terms that Function returns.
         FOR_EACH = 68; // Sequence, Function(1) -> OBJECT
<SNIP...>
```

**Comment by apa512** [comment]
:+1: I had missed this change. Another reason why better test coverage is needed.
