### ISSUE TITLE
Using r/do

### ISSUE THREAD

**Issue by stephenmuss** [apa512/clj-rethinkdb#28]
I'm trying to work out how to use the `rethinkdb.query.do` function without match luck.

Consider the following query

```javascript
r.branch(r.table('foo').getAll('bar, {index: 'name'}).isEmpty(),
  r.table("foo").insert({name: "bar"}, {returnChanges: true}).do(function(x) {
    return x;
  }),
  {"exists": true}
)
```

I've tried something equivalent with clj-rethinkdb but haven't had much success

```clojure
(r/branch (-> db
              (r/table "foo")
              (r/get-all [(:name data)] {:index "name"})
              r/is-empty)
          (-> db
              (r/table "foo")
              (r/insert data {:return-changes true})
              (r/do (fn [x] x)))
          {:exists true})
```

Obviously I would live to do additional processing in the do block, but event getting this example to work has not been possible.

How can I use (r/do) properly?

**Comment by danielytics** [comment]
Use `r/fn` not `fn`.

**Comment by stephenmuss** [comment]
Missed that. Thanks @danielytics
