### ISSUE TITLE
Could someone clarify the need for this Thead/sleep call

### ISSUE THREAD

**Issue by bhurlow** [apa512/clj-rethinkdb#30]
Hi!
Wondering why this seemingly arbitrary call to `Thread/sleep` is here: https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/net.clj#L20.
Could @apa512 clarify this? 

Thanks

**Comment by danielcompton** [comment]
I too have wondered about this. 

I think the idea is that when we have something which doesn't complete in a single call, we send a CONTINUE to the server. We don't want to just keep sending CONTINUE to the server in a tight loop because we could overfill the buffer. 

However this probably isn't the best way of implementing it, and leads to a noticeable 250ms lag when streaming change feeds to clients.

**Comment by danielcompton** [comment]
It seems like a good candidate for a core.async channel (my protestations against presenting a core.async API in other issues here notwithstanding).

**Comment by apa512** [comment]
This was to prevent ```changes``` from constantly sending queries. But 250 ms is too much of a delay, if it's even necessary at all.

**Comment by bhurlow** [comment]
Looks like responses to changes queries become Cursors. When cursors are seq'd they wait 250ms until sending a continue. Sort of similar to the Datomic tx-report-queue. I'll toy around with a smaller delay or none at all

**Comment by danielytics** [comment]
If it checks whether a query is already in flight (and if so, blocks until there is a response), can the delay be removed?

**Comment by bhurlow** [comment]
@danielytics that's what it seems like to me

**Comment by bhurlow** [comment]
The 250ms delay will also apply to any larger size query that returns a Cursor, not just `changes` queries I believe

**Comment by yurrriq** [comment]
> It seems like a good candidate for a core.async channel (my protestations against presenting a core.async API in other issues here notwithstanding).

:+1:

**Comment by danielcompton** [comment]
This could also be an opportunity to unify the different types of results that can be returned from queries. At the moment, in user code you need to handle a cursor and a realised result set coming back from the same query. These could be unified perhaps closer to how the JS driver always returns a cursor for you to act on.

**Comment by bhurlow** [comment]
@danielcompton agreed. Opportunity to unify the interface. 

Seems like people get a bit confused about why some queries return cursors and what they are (from https://github.com/apa512/clj-rethinkdb/issues/16)
> …but this produces a #<Cursor rethinkdb.net.Cursor@2c9b666e>, which is not what I'd expect after reading http://www.rethinkdb.com/docs/table-joins/ 

The cursor idea in general though is a good one. It allows for continued queries and lazy access to stuff like changes. Perhaps better documentation on the cursors would help

**Comment by bhurlow** [comment]
:ice_cream:
