### ISSUE TITLE
Create a gitter room for clj-rethinkdb?

### ISSUE THREAD

**Issue by jwr** [apa512/clj-rethinkdb#34]
How about creating a gitter.im room for this repository? For the moment the only method to talk between developers is to file an issue, which is rather heavyweight. Gitter rooms work well, they tend to have a limited audience and are easy to maintain.

**Comment by danielcompton** [comment]
I'd prefer a mailing list personally, but am open to what others like.

**Comment by bhurlow** [comment]
Some people are using slack for similar purposes: http://rauchg.com/slackin/

**Comment by jwr** [comment]
Yes. Gitter seems to be better, as it has excellent integration with github (you can reference issues, etc). A single click from a github repo brings you right into the chat room for that repo.

**Comment by bhurlow** [comment]
I'd be happy to try it out

**Comment by apa512** [comment]
gitter has worked well for me in the past. Let's try it out: https://gitter.im/apa512/clj-rethinkdb
