### ISSUE TITLE
Allow specifying the default db context in connect

### ISSUE THREAD

**Issue by danielcompton** [apa512/clj-rethinkdb#38]
The RethinkDB drivers allow the user to specify a default DB context to execute queries in. It would be good to allow this, and probably worth adding a timeout option as well for connections.

> Create a new connection to the database server. Accepts the following options:

> * host: the host to connect to (default localhost).
> * port: the port to connect on (default 28015).
> * db: the default database (default test).
> * authKey: the authentication key (default none).
> * timeout: timeout period in seconds for the connection to be opened (default 20).
> If the connection cannot be established, a RqlDriverError will be passed to the callback instead of a connection.

**Comment by bhurlow** [comment]
so you can set up the client to always use a specific db? This would be preferable over calling `r/db/` in every query for sure

**Comment by danielcompton** [comment]
http://rethinkdb.com/api/javascript/connect/

**Comment by bhurlow** [comment]
yes to this

**Comment by danielcompton** [comment]
Looks like this is sent as a global optarg to the RethinkDB server, judging from the JS driver implementation.
