### ISSUE TITLE
Strange error after many successful operations

### ISSUE THREAD

**Issue by podviaznikov** [apa512/clj-rethinkdb#4]
I was inserting a lot of documents into rethinkdb and everything was working but suddenly I got following error:

```
Caused by: java.lang.AssertionError: Assert failed: (= token recvd-token)
	at rethinkdb.net$read_response.invoke(net.clj:29)
	at rethinkdb.net$send_query.invoke(net.clj:42)
	at rethinkdb.net$send_start_query.invoke(net.clj:55)
	at rethinkdb.query$run.invoke(query.clj:378)
```

I got this twice and don't have good reproduction steps. Just curious maybe you know how that may happen.

**Comment by apa512** [comment]
Are you using the same connection from multiple threads? That won't work.

Otherwise this is something that needs more investigation. Can you tell me what kind of work you've been doing when this happens?

**Comment by podviaznikov** [comment]
Yes, you are write. I was using same connection. However from one thread I was just doing reads.

So I should have one connection per thread, right?

**Comment by apa512** [comment]
That's right.
