### ISSUE TITLE
nth not supported on rethinkdb.net.Cursor

### ISSUE THREAD

**Issue by yurrriq** [apa512/clj-rethinkdb#40]
**Edit**: The following pertains to `[rethinkdb "0.9.39"]`

I'm thinking this might be user error, but when I call a query like this pseudo-code:
```clojure
(let [n 20]
  (-> (r/db db)
      (r/table "table")
      (r/eq-join "other-table" join-fn)
      (r/map map-fn)
      ;; ...
      ;; ...
      (r/limit n)
      (r/run conn)))
```

where `n` is _sufficiently large_ (seems like :-1: &forall; n, n > 10; and _usually_ :+1: &forall; n, n < 10), I end up with a `rethinkdb.net.Cursor` on which I'm not able to call [`distinct-by`][1]. Instead, I get an error like:
> UnsupportedOperationException nth not supported on this type: Cursor  clojure.lang.RT.nthFrom (RT.java:874)

=====

Can someone help me understand how I can get an ISeqable collection out of a `Cursor`?
Or, help me adjust my queries so I get Clojure collections instead of `Cursor`s?

[1]: https://github.com/weavejester/medley/blob/0314d90860bf62b74273022fd9ddbb7de47d9420/src/medley/core.cljx#L173-L186

Thanks!

**Comment by yurrriq** [comment]
If I call my query with `(let [n 9] #_...)` it seems about half of the time I get a collection and the other half a `Cursor`..

**Comment by yurrriq** [comment]
Basically a duplicate of #16. My bad. Related: #30

**Comment by yurrriq** [comment]
I rewrote `distinct-by` to avoid nth (caused by the vector destructuring) and now my query is throwing exceptions with causes like:
> "Token 74 not in stream cache."

from [net.clj:113][https://github.com/apa512/clj-rethinkdb/blob/fb1423fafc6cc4c5e487d744f40c424e54ba3882/src/rethinkdb/net.clj#L113]

Please advise.

**Comment by yurrriq** [comment]
Gah. Sorry for all the trouble.

I rewrote `distinct-by` again, this time without the [`lazy-seq`][1] wrapper and everything is working great.

For anyone with a similar issue that reads this:
- Don't use `lazy-seq` when consuming a `Cursor`
- `Cursor`s are `ISeqable`
- Refer to #16 for more information

[1]: https://github.com/weavejester/medley/blob/0314d90860bf62b74273022fd9ddbb7de47d9420/src/medley/core.cljx#L178

**Comment by danielcompton** [comment]
@yurrriq I have a PR open which presents a core.async interface for queries which unifies cursors and results. You might find that useful as an alternative.

**Comment by yurrriq** [comment]
:+1: I actually worked up a simple core.async wrapper today too. I'm looking forward to reading your code tomorrow.
