### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by danielcompton** [apa512/clj-rethinkdb#45]
@apa512 what's the versioning scheme for this library? It could be good if we followed either the RethinkDB protocol versions, or RethinkDB database versions. Semver is also fine too. What are your thoughts?

**Comment by apa512** [comment]
Currently semver.

**Comment by arrdem** [comment]
Is there a good reason to do something other than SemVer with notes about the supported/targeted RethinkDB api version?

**Comment by bhurlow** [comment]
how quickly do the rethinkdb people update their protocol version? if thats like a yearly thing then I think semver makes more sense.

**Comment by danielcompton** [comment]
Semver makes sense, I just wasn't sure why we were going from `0.8.39` to `0.9.39` instead of to `0.9.0`. https://github.com/apa512/clj-rethinkdb/commit/a8438652dd295865850d75bdbb1576e77801a0ba

**Comment by apa512** [comment]
That's my limited understanding of semver. 0.9.0 would indeed make more sense now that I think about it.

I guess we should start following "real" semver from now on.

**Comment by danielcompton** [comment]
Semver it is.
