### ISSUE TITLE
Name binding does not work properly with nested fn's

### ISSUE THREAD

**Issue by danielytics** [apa512/clj-rethinkdb#5]
When nesting fn's, the name bindings of the outer fn get overwritten by the name bindings of the inner fn's and cannot be accessed in the inner fn's.

Nesting works as expected in the official javascript driver.

---

The ```test``` table looks like this:
```clojure
{:id "40cd4261-aa72-4427-877b-da45abe4142b" :field [{:name "foo"}]}
```

The javascript query looks like this:
```javascript
r.table('test').get('40cd4261-aa72-4427-877b-da45abe4142b')('field')
 .map(function(x){
  return {a: x('name'),
          b: r.expr(["x", "y", "z"]).map(function(y){
             return x
          })
       }
  })
```

And its output:
```javascript
[
    {
        "a":  "foo" ,
        "b": [ 
            {
                "id":  "afc9cb64-af3d-4cae-8993-fc5d35ebd6ee" ,
                "name":  "foo" ,
            },
            {
                "id":  "afc9cb64-af3d-4cae-8993-fc5d35ebd6ee" ,
                "name":  "foo" ,
            },
            {
                "id":  "afc9cb64-af3d-4cae-8993-fc5d35ebd6ee" ,
                "name":  "foo" ,
            }
        ]
    }
]
```

However, when I try to run this in Revise, referencing ```x``` inside the nested lambda does not work.

The Clojure query:
```clojure
(-> (r/db :test) 
    (r/table :test)
    (r/get "40cd4261-aa72-4427-877b-da45abe4142b")
    (r/get-field :field)
    (r/map
      (r/fn [x]
        {:a (r/get-field x :name)
         :b (-> ["x" "y" "z"]
                (r/map
                  (r/fn [y]
                    x))})))
```

And its output:
```clojure
[{:a "foo"
  :b ["x" "y" "z"]}]
```

That is, the inner fn clobbers the binding of the outer one.

---

I reported the exact same issue on the Revise driver some months ago (issue #14), see the discussion there for more details. Basically what is happening is that RethinkDB variables are unique integer IDs, but the fn code https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/query.clj#L9-L16 assigns integers starting at 0 for each fn - therefore both x and y in my code above are assigned 0 and RethinkDB treats them as the same variable.

In my own Revise code, I wrote my own lambda function which keeps track of the latest ID in a global atom and therefore each variable binding is given a unique integer. The "real" solution would be to have something like rethinkdb.query/run walk the AST before serializing to JSON and assigning ID's then - ie unique to each query, not globally. This would also allow it to reuse IDs that go out of scope (I don't know if this will help RethinkDB memory usage or not, I'm not sure how it handles variables internally, but it *seems* like a good idea to me).

**Comment by danielytics** [comment]
This temporary fix works for me. I think it can be improved upon, but if somebody needs something for now, this should work:

Change `fn` to:
```clojure
(defmacro fn [args & [body]]
  (let [func-args (mapv keyword args)
        arg-replacements (zipmap args
                                 (clojure.core/map (clojure.core/fn [n]
                                                     (term :VAR [(get func-args n)]))
                                                   (range)))
        func-terms (clojure.walk/postwalk-replace arg-replacements body)]
    (term :FUNC [func-args func-terms])))
```

Add this function:
```clojure
(defn eplace-vars [query]
  (let [vars      (atom {})
        var-count (atom 0)]
    (clojure.walk/prewalk
      (fn [node]
        (condp = (:rethinkdb.query-builder/term node)
          :FUNC
            (let [[args body] (:rethinkdb.query-builder/args node)
                  var-ids     (into [] (take (count args)
                                             (iterate inc @var-count)))]
              (if-not (some (complement keyword) args)
                (do
                  (swap! vars merge (into {} (map vector args var-ids)))
                  (reset! var-count (inc (peek var-ids)))
                  (assoc node :rethinkdb.query-builder/args [var-ids body]))
                node))
          :VAR
            (update-in node [:rethinkdb.query-builder/args] #(mapv @vars %))
          node))
      query)))
```

And then modify run from ` (send-start-query conn token args)` to ` (send-start-query conn token (replace-vars args))`

The `replace-vars` function can most likely be improved *a lot* (eg getting rid of those atoms... keeping the variables in a stack to reuse IDs when they go out of scope...), but I don't have time to look at this further for now.

**Comment by apa512** [comment]
Great! I'll look more into this shortly.

**Comment by apa512** [comment]
Seems to work now. Please let me know if you encounter any other problems or if you can think of a cleaner solution.

```clojure
(is (= [{:a {:foo "bar"}
               :b [1 2]}]
             (run (-> [{:foo "bar"}]
                      (r/map (r/fn [x]
                               {:a x
                                :b (-> [1 2]
                                       (r/map (r/fn [x]
                                                x)))}))))))
      (is (= [{:a {:foo "bar"}
               :b [{:foo "bar"} {:foo "bar"}]}]
             (run (-> [{:foo "bar"}]
                      (r/map (r/fn [x]
                               {:a x
                                :b (-> [1 2]
                                       (r/map (r/fn [y]
                                                x)))}))))))
```

**Comment by danielytics** [comment]
Awesome, thanks. I'll let you know if I encounter any issues or if I think of a better approach :)
