### ISSUE TITLE
Turn query vector into query map

### ISSUE THREAD

**Issue by danielcompton** [apa512/clj-rethinkdb#53]
To avoid more bugs like #52 it could be good to turn the query vector into a query map. It could look something like: 

```clj
{:token 5
 :query ...
 :json-query ... ; turned into raw JSON arrays
 :query-type
 :global-optargs}
```

This would make it easier to put assertions in various places to ensure that queries are being constructed correctly.

**Comment by dev-hartmann** [comment]
Hey, I would like to tackle this issue if you don't mind. I am still new to Clojure, so a few pointers would be appreciated!

**Comment by danielcompton** [comment]
Take a look at https://github.com/apa512/clj-rethinkdb/pull/52/commits/53cea150267713eff9ed98ab4f5373c346f56a23, and the fixes I made. The main change is to change the vector that represents the query into a map. Feel free to jump into the Gitter chat for more help.

**Comment by apa512** [comment]
We're now using a map with ```[:query :query-type :token]``` keys.
