### ISSUE TITLE
Move to Clojure 1.7?

### ISSUE THREAD

**Issue by danielcompton** [apa512/clj-rethinkdb#56]
Now that Clojure 1.7 is officially released, what are people's thoughts about moving this library to Clojure 1.7 in the future? Is anyone using Clojure 1.6 that isn't planning/able to upgrade? I'm particularly interested in hearing from anyone who can't upgrade.

The main motivation for requiring 1.7 is so that it would be possible to move to `cljc` files and generate queries on the client. Transducers may also be useful in the future, but not immediately.

**Comment by jwr** [comment]
Just as a data point — most people using Apache Storm (that includes one application in our company) are still stuck on 1.5. A beta supporting 1.6 came out recently. I don't know about 1.7. So there are sometimes cases where people are legitimately stuck on older versions.

That said, I do not think we should worry. I'd expect people using clj-rethinkdb to have newer systems, building new applications using new components. If there are good reasons for moving to 1.7 (and `cljc` support is definitely one of them), I'd say go for it.

**Comment by apa512** [comment]
I'm for it.

**Comment by danielytics** [comment]
I'm for it too (but I already use 1.7 for cljc support).

**Comment by bhurlow** [comment]
yes to 1.7

**Comment by belucid** [comment]
+1 on moving to 1.7. People on 1.6 and before can just use earlier releases of this lib.

**Comment by danielytics** [comment]
A note should be left in the readme then letting people know which version to use for 1.6.

I suggest making an 0.10.0 release as the last 1.6 release and then immediately making a 0.11.0 release for 1.7 and then all future development goes into 0.11.x and above.

**Comment by danielcompton** [comment]
Closed by #59.
