### ISSUE TITLE
RethinkDB arrays don't get turned into Clojure vectors

### ISSUE THREAD

**Issue by danielytics** [apa512/clj-rethinkdb#6]
This may be a feature, rather than a bug, but it tripped me up (I guess because I converted code written with Revise, which does convert them to vectors). It seems to me that vectors would be more useful as they map more closely to js (and therefore RethinkDB) vectors.

I'd also prefer to avoid having to convert them in client code especially if they're nested in documents, although I understand if you prefer keeping them as seqs (especially since not all users will need this and it would therefore incur an unneeded cost).

**Comment by apa512** [comment]
Not sure I understand. Is this about arrays being returned as LazySeqs instead of vectors? That's not really something I've thought much about.

Does it make any difference in practice?

**Comment by danielytics** [comment]
Yes, that's what I meant.

It probably doesn't make any real difference and the more I think about it, the more I'm thinking LazySeqs are probably the right thing. Just means I have to modify some existing code that was written to expect revise's output (ie vectors) and I'm lazy ;-)

I guess you can close this then.

**Comment by apa512** [comment]
I decided to convert arrays to vectors after all.
