### ISSUE TITLE
Source links in API reference docs are wrong

### ISSUE THREAD

**Issue by belucid** [apa512/clj-rethinkdb#63]
The "view source" links in the [API reference docs](http://apa512.github.io/clj-rethinkdb/) don't point to the right line numbers.

For example, this is the link for query/replace:

https://github.com/apa512/clj-rethinkdb/blob/master/src/rethinkdb/query.clj#L110

Actual line number is 137, not 110.

**Comment by danielcompton** [comment]
Thanks for this, we need to update the Codox docs. Sorry for the inconvenience.

**Comment by danielcompton** [comment]
Hey sorry about this, I've updated the docs. However the larger issue is that we're not pointing to a tag when we generate the docs so master will slowly drift from whatever was created when we release. I'll need to fix this in a more longterm way.

**Comment by danielcompton** [comment]
I've re-pushed the docs to point to the 0.10.1 release tag. I'm not sure how to handle this automatically, it may need to be a manual thing to update `[:codox :src-dir-uri] "https://github.com/apa512/clj-rethinkdb/blob/0.10.1/"` in `project.clj`.

**Comment by danielytics** [comment]
If we properly follow SemVer (ie revisions don't change the public facing API), then this should only be necessary when the API changes (on a major or minor release, not on a revision/bugfix).

I'm not sure how many API changes we can expect in the future (I'm hoping not many unless RethinkDB adds a bunch of new features).
