### ISSUE TITLE
Best approach for connection

### ISSUE THREAD

**Issue by alolis** [apa512/clj-rethinkdb#91]
I see in your example that you use the following:

```clojure
(with-open [conn (r/connect :host "127.0.0.1" :port 28015 :db "test")]
    .......
)
```

Is this the best approach (to close and open a connection all the time) if the application is accessing the server very often and different functions are used?

Isn't it better to define a connection object once and use it through the application?

````clojure
(def conn (r/connect :host "127.0.0.1" :port 28015 :db "test"))
````

or will the above cause performance issues because the connection stays open (?)

**Comment by danielytics** [comment]
Yes, reusing a single connection is higher performance than
recreating/reconnecting every time.

**Comment by alolis** [comment]
@danielytics , cheers. Just wanted to make sure :)
