### ISSUE TITLE
Adding Maven group ID to clj-rethinkdb project

### ISSUE THREAD

**Issue by danielcompton** [apa512/clj-rethinkdb#92]
With the imminent release of an official [Java driver](https://github.com/rethinkdb/rethinkdb/tree/josh/java-driver/drivers/java) from RethinkDB it might be a good time to re-examine the group ID we're using (`rethinkdb`) as it may conflict with the official one or at least be confusing for people.

@apa512 do you have a preference for this? Something like `com.apa512` could work, or any other domain you control.

On the other hand maybe this isn't a big deal and it's fine to stay as it is. Thoughts welcome.

https://github.com/rethinkdb/rethinkdb/issues/3930

**Comment by apa512** [comment]
Sure, changing to com.apa512.rethinkdb seems like a good idea.

**Comment by danielcompton** [comment]
@apa512 do you own apa512.com?

**Comment by apa512** [comment]
Yes.

**Comment by danielcompton** [comment]
Cool. So the coordinates will change from `[rethinkdb "0.11.0"]` to `[com.apa512/rethinkdb "0.11.0"]`. Sound good?

**Comment by apa512** [comment]
I like it :+1:
