### ISSUE TITLE
java.lang.Exception: Array over size limit `100000`.

### ISSUE THREAD

**Issue by Chris-Andrews** [apa512/clj-rethinkdb#94]
I got the message:
```java.lang.Exception: Array over size limit `100000`.```
when trying to insert a large data structure using:
```(-> (r/db db) (r/table table) (r/insert data) (r/run conn))```

The offending data appears to be a map that contains a 107,700 x 3 vector and another 217,524 x 3 vector. Maybe I'm just doing something I shouldn't be doing with rethinkdb, but I thought this could be a bug since I'm getting a java exception. Any input is appreciated.

**Comment by apa512** [comment]
RethinkDB inserts are limited to 100,000 elements.

**Comment by danielcompton** [comment]
Initially I thought we might be able to present an option to alter this, but I was mistaken.

> arrayLimit: the maximum numbers of array elements that can be returned by a query (default: 100,000). This affects all ReQL commands that return arrays. Note that it has no effect on the size of arrays being written to the database; those always have an upper limit of 100,000 elements. - [run JS API docs](https://rethinkdb.com/api/javascript/run/)

It's not really a bug, more a limitation of the underlying database. I'm not sure if there's much we can do about this?

**Comment by Chris-Andrews** [comment]
Hi, thanks a lot for clarifying that for me.

@danielcompton - If it's possible to change this message I think people may have an easier time figuring out what's going on if the error message referenced RethinkDB and/or the specific operation:
```java.lang.Exception: Can't insert arrays over RethinkDB size limit of `100000`.```

Before I opened the issue, I tried searching this repo for that message, "size limit", and the number 100000 and couldn't find anything, so I thought maybe I was just using the API incorrectly and causing some kind of error that wasn't directly related to RethinkDB.

**Comment by danielcompton** [comment]
@Chris-Andrews when we get an exception from RethinkDB, we just get a string `"Can't insert arrays over size limit of `100000``. However we could do any or all of:

1. Prepend the message with something like `RethinkDB exception:` 
2. Use a custom RethinkDB Exception type
3. Document exception behaviour.

**Comment by Chris-Andrews** [comment]
I would consider option 1 or 2 a useful addition. 3 is a bonus, but I'd imagine if you saw ```RethinkDB exception:``` you would know to start looking into RethinkDB limitations related to what you tried to do.
