### ISSUE TITLE
r/get-field no attribute exception

### ISSUE THREAD

**Issue by timstott** [apa512/clj-rethinkdb#99]
The data sample below doesn't allow me to use `r/get-field`.

```
{ name: "Bob" },
{ name: "Alice", last_name: "Dupon" }
```

```clojure
(r/get-field :last_name) ;; throws the following
Exception No attribute `last_name` in object:
```

Any thoughts on overcoming this issue? :smile: (normalizing the data isn't relevant)

**Comment by danielytics** [comment]
You need to protect against this using http://rethinkdb.com/api/javascript/#default but it doesn't appear to be implemented in clj-rethinkdb (which is odd because I thought I'd used it, but I guess not). There was issue #29 but its been closed.

A workaround might be something like this:
```clj
(r/branch
  (r/has-fields obj :last_name)
  (r/get-field obj :last_name)
  nil) ; or some other default value```

Ugly, I know, but best you can do without `(r/default ...)`

**Comment by yurrriq** [comment]
Adding support for `optargs`, as in #43 should do the trick, no?

**Comment by timstott** [comment]
@yurrriq @danielytics Thanks a lot for the suggestions :bow:. I'm going to explore both :smiley_cat:.
Adding support for `optagrs` sure sounds interesting.

**Comment by danielytics** [comment]
@yurrriq's idea of adding optargs would be really nice. Definitely a nice clean way of handling it (even more so than default!), but of course you'd have to implement it. If you need something in the meantime then the branch approach is a workaround.

**Comment by danielcompton** [comment]
RethinkDB doesn't support optargs for `get-field`, but you can use the general purpose `default` function for the same purpose. I've added `default` in 90b58cd to fix this. @timstott take a look at [the tests](https://github.com/apa512/clj-rethinkdb/commit/90b58cd14179fb4eec6e8a28387fe4eda1397adb#diff-74cf348d1e5657b57ef5a7ee09824c3bR117) for an example of how to use `default`.

**Comment by yurrriq** [comment]
:+1:

**Comment by timstott** [comment]
@danielcompton works like a charm. Thanks a lot.
